// stocks_data.js
// Database saham IDX: 956 tickers dengan metadata (Papan & Indeks)
// Update file ini untuk menambah/edit data saham dan kategorinya

// 956 tickers
const TK=["AADI", "AALI", "ABBA", "ABDA", "ABMM", "ACES", "ACRO", "ACST", "ADCP", "ADES", "ADHI", "ADMF", "ADMG", "ADMR", "ADRO", "AEGS", "AGAR", "AGII", "AGRO", "AGRS", "AHAP", "AIMS", "AISA", "AKKU", "AKPI", "AKRA", "AKSI", "ALDO", "ALII", "ALKA", "ALMI", "ALTO", "AMAG", "AMAN", "AMAR", "AMFG", "AMIN", "AMMN", "AMMS", "AMOR", "AMRT", "ANDI", "ANJT", "ANTM", "APEX", "APIC", "APII", "APLI", "APLN", "ARCI", "AREA", "ARGO", "ARII", "ARKA", "ARKO", "ARMY", "ARNA", "ARTA", "ARTI", "ARTO", "ASBI", "ASDM", "ASGR", "ASHA", "ASII", "ASJT", "ASLC", "ASLI", "ASMI", "ASPI", "ASPR", "ASRI", "ASRM", "ASSA", "ATAP", "ATIC", "ATLA", "AUTO", "AVIA", "AWAN", "AXIO", "AYAM", "AYLS", "BABP", "BABY", "BACA", "BAIK", "BAJA", "BALI", "BANK", "BAPA", "BAPI", "BATA", "BATR", "BAUT", "BAYU", "BBCA", "BBHI", "BBKP", "BBLD", "BBMD", "BBNI", "BBRI", "BBRM", "BBSI", "BBSS", "BBTN", "BBYB", "BCAP", "BCIC", "BCIP", "BDKR", "BDMN", "BEBS", "BEEF", "BEER", "BEKS", "BELI", "BELL", "BESS", "BEST", "BFIN", "BGTG", "BHAT", "BHIT", "BIKA", "BIKE", "BIMA", "BINA", "BINO", "BIPI", "BIPP", "BIRD", "BISI", "BJBR", "BJTM", "BKDP", "BKSL", "BKSW", "BLES", "BLOG", "BLTA", "BLTZ", "BLUE", "BMAS", "BMBL", "BMHS", "BMRI", "BMSR", "BMTR", "BNBA", "BNBR", "BNGA", "BNII", "BNLI", "BOAT", "BOBA", "BOGA", "BOLA", "BOLT", "BOSS", "BPFI", "BPII", "BPTR", "BRAM", "BREN", "BRIS", "BRMS", "BRNA", "BRPT", "BRRC", "BSBK", "BSDE", "BSIM", "BSML", "BSSR", "BSWD", "BTEK", "BTEL", "BTON", "BTPN", "BTPS", "BUAH", "BUDI", "BUKA", "BUKK", "BULL", "BUMI", "BUVA", "BVIC", "BWPT", "BYAN", "CAKK", "CAMP", "CANI", "CARE", "CARS", "CASA", "CASH", "CASS", "CBDK", "CBMF", "CBPE", "CBRE", "CBUT", "CCSI", "CDIA", "CEKA", "CENT", "CFIN", "CGAS", "CHEK", "CHEM", "CHIP", "CINT", "CITA", "CITY", "CLAY", "CLEO", "CLPI", "CMNP", "CMNT", "CMPP", "CMRY", "CNKO", "CNMA", "CNTX", "COAL", "COCO", "COIN", "COWL", "CPIN", "CPRI", "CPRO", "CRAB", "CRSN", "CSAP", "CSIS", "CSMI", "CSRA", "CTBN", "CTRA", "CTTH", "CUAN", "CYBR", "DAAZ", "DADA", "DART", "DATA", "DAYA", "DCII", "DEAL", "DEFI", "DEPO", "DEWA", "DEWI", "DFAM", "DGIK", "DGNS", "DGWG", "DIGI", "DILD", "DIVA", "DKFT", "DKHH", "DLTA", "DMAS", "DMMX", "DMND", "DNAR", "DNET", "DOID", "DOOH", "DOSS", "DPNS", "DPUM", "DRMA", "DSFI", "DSNG", "DSSA", "DUCK", "DUTI", "DVLA", "DWGL", "DYAN", "EAST", "ECII", "EDGE", "EKAD", "ELIT", "ELPI", "ELSA", "ELTY", "EMAS", "EMDE", "EMTK", "ENAK", "ENRG", "ENVY", "ENZO", "EPAC", "EPMT", "ERAA", "ERAL", "ERTX", "ESIP", "ESSA", "ESTA", "ESTI", "ETWA", "EURO", "EXCL", "FAPA", "FAST", "FASW", "FILM", "FIMP", "FIRE", "FISH", "FITT", "FLMC", "FMII", "FOLK", "FOOD", "FORE", "FORU", "FPNI", "FUJI", "FUTR", "FWCT", "GAMA", "GDST", "GDYR", "GEMA", "GEMS", "GGRM", "GGRP", "GHON", "GIAA", "GJTL", "GLOB", "GLVA", "GMFI", "GMTD", "GOLD", "GOLF", "GOLL", "GOOD", "GOTO", "GPRA", "GPSO", "GRIA", "GRPH", "GRPM", "GSMF", "GTBO", "GTRA", "GTSI", "GULA", "GUNA", "GWSA", "GZCO", "HADE", "HAIS", "HAJJ", "HALO", "HATM", "HBAT", "HDFA", "HDIT", "HEAL", "HELI", "HERO", "HEXA", "HGII", "HILL", "HITS", "HKMU", "HMSP", "HOKI", "HOME", "HOMI", "HOPE", "HOTL", "HRME", "HRTA", "HRUM", "HUMI", "HYGN", "IATA", "IBFN", "IBOS", "IBST", "ICBP", "ICON", "IDEA", "IDPR", "IFII", "IFSH", "IGAR", "IIKP", "IKAI", "IKAN", "IKBI", "IKPM", "IMAS", "IMJS", "IMPC", "INAF", "INAI", "INCF", "INCI", "INCO", "INDF", "INDO", "INDR", "INDS", "INDX", "INDY", "INET", "INKP", "INOV", "INPC", "INPP", "INPS", "INRU", "INTA", "INTD", "INTP", "IOTF", "IPAC", "IPCC", "IPCM", "IPOL", "IPPE", "IPTV", "IRRA", "IRSX", "ISAP", "ISAT", "ISEA", "ISSP", "ITIC", "ITMA", "ITMG", "JARR", "JAST", "JATI", "JAWA", "JAYA", "JECC", "JGLE", "JIHD", "JKON", "JMAS", "JPFA", "JRPT", "JSKY", "JSMR", "JSPT", "JTPE", "KAEF", "KAQI", "KARW", "KAYU", "KBAG", "KBLI", "KBLM", "KBLV", "KBRI", "KDSI", "KDTN", "KEEN", "KEJU", "KETR", "KIAS", "KICI", "KIJA", "KING", "KINO", "KIOS", "KJEN", "KKES", "KKGI", "KLAS", "KLBF", "KLIN", "KMDS", "KMTR", "KOBX", "KOCI", "KOIN", "KOKA", "KONI", "KOPI", "KOTA", "KPIG", "KRAS", "KREN", "KRYA", "KSIX", "KUAS", "LABA", "LABS", "LAJU", "LAND", "LAPD", "LCGP", "LCKM", "LEAD", "LFLO", "LIFE", "LINK", "LION", "LIVE", "LMAS", "LMAX", "LMPI", "LMSH", "LOPI", "LPCK", "LPGI", "LPIN", "LPKR", "LPLI", "LPPF", "LPPS", "LRNA", "LSIP", "LTLS", "LUCK", "LUCY", "MABA", "MAGP", "MAHA", "MAIN", "MANG", "MAPA", "MAPB", "MAPI", "MARI", "MARK", "MASB", "MAXI", "MAYA", "MBAP", "MBMA", "MBSS", "MBTO", "MCAS", "MCOL", "MCOR", "MDIA", "MDIY", "MDKA", "MDKI", "MDLA", "MDLN", "MDRN", "MEDC", "MEDS", "MEGA", "MEJA", "MENN", "MERI", "MERK", "META", "MFMI", "MGLV", "MGNA", "MGRO", "MHKI", "MICE", "MIDI", "MIKA", "MINA", "MINE", "MIRA", "MITI", "MKAP", "MKNT", "MKPI", "MKTR", "MLBI", "MLIA", "MLPL", "MLPT", "MMIX", "MMLP", "MNCN", "MOLI", "MORA", "MPIX", "MPMX", "MPOW", "MPPA", "MPRO", "MPXL", "MRAT", "MREI", "MSIE", "MSIN", "MSJA", "MSKY", "MSTI", "MTDL", "MTEL", "MTFN", "MTLA", "MTMH", "MTPS", "MTRA", "MTSM", "MTWI", "MUTU", "MYOH", "MYOR", "MYTX", "NAIK", "NANO", "NASA", "NASI", "NATO", "NAYZ", "NCKL", "NELY", "NEST", "NETV", "NFCX", "NICE", "NICK", "NICL", "NIKL", "NINE", "NIRO", "NISP", "NOBU", "NPGF", "NRCA", "NSSS", "NTBK", "NUSA", "NZIA", "OASA", "OBAT", "OBMD", "OCAP", "OILS", "OKAS", "OLIV", "OMED", "OMRE", "OPMS", "PACK", "PADA", "PADI", "PALM", "PAMG", "PANI", "PANR", "PANS", "PART", "PBID", "PBRX", "PBSA", "PCAR", "PDES", "PDPP", "PEGE", "PEHA", "PEVE", "PGAS", "PGEO", "PGJO", "PGLI", "PGUN", "PICO", "PIPA", "PJAA", "PJHB", "PKPK", "PLAN", "PLAS", "PLIN", "PMJS", "PMMP", "PMUI", "PNBN", "PNBS", "PNGO", "PNIN", "PNLF", "PNSE", "POLA", "POLI", "POLL", "POLU", "POLY", "POOL", "PORT", "POSA", "POWR", "PPGL", "PPRE", "PPRI", "PPRO", "PRAY", "PRDA", "PRIM", "PSAB", "PSAT", "PSDN", "PSGO", "PSKT", "PSSI", "PTBA", "PTDU", "PTIS", "PTMP", "PTMR", "PTPP", "PTPS", "PTPW", "PTRO", "PTSN", "PTSP", "PUDP", "PURA", "PURE", "PURI", "PWON", "PYFA", "PZZA", "RAAM", "RAFI", "RAJA", "RALS", "RANC", "RATU", "RBMS", "RCCC", "RDTX", "REAL", "RELF", "RELI", "RGAS", "RICY", "RIGS", "RIMO", "RISE", "RLCO", "RMKE", "RMKO", "ROCK", "RODA", "RONY", "ROTI", "RSCH", "RSGK", "RUIS", "RUNS", "SAFE", "SAGE", "SAME", "SAMF", "SAPX", "SATU", "SBAT", "SBMA", "SCCO", "SCMA", "SCNP", "SCPI", "SDMU", "SDPC", "SDRA", "SEMA", "SFAN", "SGER", "SGRO", "SHID", "SHIP", "SICO", "SIDO", "SILO", "SIMA", "SIMP", "SINI", "SIPD", "SKBM", "SKLT", "SKRN", "SKYB", "SLIS", "SMAR", "SMBR", "SMCB", "SMDM", "SMDR", "SMGA", "SMGR", "SMIL", "SMKL", "SMKM", "SMLE", "SMMA", "SMMT", "SMRA", "SMRU", "SMSM", "SNLK", "SOCI", "SOFA", "SOHO", "SOLA", "SONA", "SOSS", "SOTS", "SOUL", "SPMA", "SPRE", "SPTO", "SQMI", "SRAJ", "SRIL", "SRSN", "SRTG", "SSIA", "SSMS", "SSTM", "STAA", "STAR", "STRK", "STTP", "SUGI", "SULI", "SUNI", "SUPA", "SUPR", "SURE", "SURI", "SWAT", "SWID", "TALF", "TAMA", "TAMU", "TAPG", "TARA", "TAXI", "TAYS", "TBIG", "TBLA", "TBMS", "TCID", "TCPI", "TDPM", "TEBE", "TECH", "TELE", "TFAS", "TFCO", "TGKA", "TGRA", "TGUK", "TIFA", "TINS", "TIRA", "TIRT", "TKIM", "TLDN", "TLKM", "TMAS", "TMPO", "TNCA", "TOBA", "TOOL", "TOPS", "TOSK", "TOTL", "TOTO", "TOWR", "TOYS", "TPIA", "TPMA", "TRAM", "TRGU", "TRIL", "TRIM", "TRIN", "TRIO", "TRIS", "TRJA", "TRON", "TRST", "TRUE", "TRUK", "TRUS", "TSPC", "TUGU", "TYRE", "UANG", "UCID", "UDNG", "UFOE", "ULTJ", "UNIC", "UNIQ", "UNIT", "UNSP", "UNTD", "UNTR", "UNVR", "URBN", "UVCR", "VAST", "VERN", "VICI", "VICO", "VINS", "VISI", "VIVA", "VKTR", "VOKS", "VRNA", "VTNY", "WAPO", "WEGE", "WEHA", "WGSH", "WICO", "WIDI", "WIFI", "WIIM", "WIKA", "WINE", "WINR", "WINS", "WIRG", "WMPP", "WMUU", "WOMF", "WOOD", "WOWS", "WSBP", "WSKT", "WTON", "YELO", "YOII", "YPAS", "YULE", "YUPI", "ZATA", "ZBRA", "ZINC", "ZONE", "ZYRX"];

const TM={
  "AADI":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "AALI":{p:"Utama",i:["ISSI"]},
  "ABBA":{p:"Pemantauan Khusus",i:[]},
  "ABDA":{p:"Pemantauan Khusus",i:[]},
  "ABMM":{p:"Utama",i:["ISSI"]},
  "ACES":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "ACRO":{p:"Pengembangan",i:[]},
  "ACST":{p:"Pengembangan",i:["ISSI"]},
  "ADCP":{p:"Pengembangan",i:["ISSI"]},
  "ADES":{p:"Pengembangan",i:["ISSI"]},
  "ADHI":{p:"Utama",i:["BUMN", "ISSI"]},
  "ADMF":{p:"Pengembangan",i:[]},
  "ADMG":{p:"Pengembangan",i:["ISSI"]},
  "ADMR":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "ADRO":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "AEGS":{p:"Akselerasi",i:[]},
  "AGAR":{p:"Pengembangan",i:["ISSI"]},
  "AGII":{p:"Pengembangan",i:["ISSI"]},
  "AGRO":{p:"Utama",i:[]},
  "AGRS":{p:"Pengembangan",i:[]},
  "AHAP":{p:"Pengembangan",i:[]},
  "AIMS":{p:"Pengembangan",i:["ISSI"]},
  "AISA":{p:"Utama",i:["ISSI"]},
  "AKKU":{p:"Pemantauan Khusus",i:["ISSI"]},
  "AKPI":{p:"Pengembangan",i:["ISSI"]},
  "AKRA":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "AKSI":{p:"Pengembangan",i:["ISSI"]},
  "ALDO":{p:"Pengembangan",i:["ISSI"]},
  "ALII":{p:"Utama",i:[]},
  "ALKA":{p:"Pengembangan",i:["ISSI"]},
  "ALMI":{p:"Pemantauan Khusus",i:[]},
  "ALTO":{p:"Pemantauan Khusus",i:[]},
  "AMAG":{p:"Pengembangan",i:[]},
  "AMAN":{p:"Pengembangan",i:["ISSI"]},
  "AMAR":{p:"Pengembangan",i:[]},
  "AMFG":{p:"Pengembangan",i:["ISSI"]},
  "AMIN":{p:"Pengembangan",i:["ISSI"]},
  "AMMN":{p:"Utama",i:["KOMPAS100", "LQ45"]},
  "AMMS":{p:"Akselerasi",i:[]},
  "AMOR":{p:"Pengembangan",i:[]},
  "AMRT":{p:"Utama",i:["KOMPAS100", "LQ45"]},
  "ANDI":{p:"Pemantauan Khusus",i:["ISSI"]},
  "ANJT":{p:"Pengembangan",i:["ISSI"]},
  "ANTM":{p:"Utama",i:["BUMN", "ISSI", "KOMPAS100", "LQ45"]},
  "APEX":{p:"Pengembangan",i:[]},
  "APIC":{p:"Pengembangan",i:[]},
  "APII":{p:"Pengembangan",i:["ISSI"]},
  "APLI":{p:"Pengembangan",i:["ISSI"]},
  "APLN":{p:"Utama",i:["ISSI"]},
  "ARCI":{p:"Pengembangan",i:["ISSI", "KOMPAS100"]},
  "AREA":{p:"Pengembangan",i:["ISSI"]},
  "ARGO":{p:"Pengembangan",i:["ISSI"]},
  "ARII":{p:"Pengembangan",i:["ISSI"]},
  "ARKA":{p:"Pemantauan Khusus",i:[]},
  "ARKO":{p:"Pengembangan",i:[]},
  "ARMY":{p:"Pemantauan Khusus",i:[]},
  "ARNA":{p:"Utama",i:["ISSI"]},
  "ARTA":{p:"Pengembangan",i:["ISSI"]},
  "ARTI":{p:"Pemantauan Khusus",i:[]},
  "ARTO":{p:"Utama",i:["KOMPAS100"]},
  "ASBI":{p:"Pengembangan",i:[]},
  "ASDM":{p:"Pengembangan",i:[]},
  "ASGR":{p:"Utama",i:["ISSI"]},
  "ASHA":{p:"Pengembangan",i:["ISSI"]},
  "ASII":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "ASJT":{p:"Pengembangan",i:[]},
  "ASLC":{p:"Pengembangan",i:["ISSI"]},
  "ASLI":{p:"Pengembangan",i:["ISSI"]},
  "ASMI":{p:"Pemantauan Khusus",i:[]},
  "ASPI":{p:"Pengembangan",i:["ISSI"]},
  "ASPR":{p:"Pengembangan",i:[]},
  "ASRI":{p:"Utama",i:["ISSI"]},
  "ASRM":{p:"Pengembangan",i:[]},
  "ASSA":{p:"Utama",i:["ISSI"]},
  "ATAP":{p:"Pengembangan",i:["ISSI"]},
  "ATIC":{p:"Pengembangan",i:["ISSI"]},
  "ATLA":{p:"Pengembangan",i:["ISSI"]},
  "AUTO":{p:"Utama",i:["ISSI"]},
  "AVIA":{p:"Utama",i:["ISSI"]},
  "AWAN":{p:"Pengembangan",i:["ISSI"]},
  "AXIO":{p:"Pengembangan",i:["ISSI"]},
  "AYAM":{p:"Pengembangan",i:["ISSI"]},
  "AYLS":{p:"Pengembangan",i:["ISSI"]},
  "BABP":{p:"Pengembangan",i:[]},
  "BABY":{p:"Pengembangan",i:["ISSI"]},
  "BACA":{p:"Utama",i:[]},
  "BAIK":{p:"Pemantauan Khusus",i:["ISSI"]},
  "BAJA":{p:"Pengembangan",i:[]},
  "BALI":{p:"Utama",i:[]},
  "BANK":{p:"Pengembangan",i:["ISSI"]},
  "BAPA":{p:"Pengembangan",i:[]},
  "BAPI":{p:"Pemantauan Khusus",i:["ISSI"]},
  "BATA":{p:"Pemantauan Khusus",i:["ISSI"]},
  "BATR":{p:"Pengembangan",i:["ISSI"]},
  "BAUT":{p:"Pemantauan Khusus",i:["ISSI"]},
  "BAYU":{p:"Utama",i:["ISSI"]},
  "BBCA":{p:"Utama",i:["KOMPAS100", "LQ45"]},
  "BBHI":{p:"Utama",i:[]},
  "BBKP":{p:"Pengembangan",i:[]},
  "BBLD":{p:"Pengembangan",i:[]},
  "BBMD":{p:"Pengembangan",i:[]},
  "BBNI":{p:"Utama",i:["KOMPAS100", "LQ45"]},
  "BBRI":{p:"Utama",i:["KOMPAS100", "LQ45"]},
  "BBRM":{p:"Pengembangan",i:["ISSI"]},
  "BBSI":{p:"Utama",i:[]},
  "BBSS":{p:"Pengembangan",i:["ISSI"]},
  "BBTN":{p:"Utama",i:["KOMPAS100", "LQ45"]},
  "BBYB":{p:"Utama",i:["KOMPAS100"]},
  "BCAP":{p:"Utama",i:[]},
  "BCIC":{p:"Pengembangan",i:[]},
  "BCIP":{p:"Pengembangan",i:["ISSI"]},
  "BDKR":{p:"Utama",i:["ISSI"]},
  "BDMN":{p:"Utama",i:[]},
  "BEBS":{p:"Pemantauan Khusus",i:[]},
  "BEEF":{p:"Pengembangan",i:["ISSI"]},
  "BEER":{p:"Pengembangan",i:[]},
  "BEKS":{p:"Pemantauan Khusus",i:[]},
  "BELI":{p:"Ekonomi Baru",i:["ISSI"]},
  "BELL":{p:"Pemantauan Khusus",i:["ISSI"]},
  "BESS":{p:"Pengembangan",i:["ISSI"]},
  "BEST":{p:"Utama",i:["ISSI"]},
  "BFIN":{p:"Utama",i:[]},
  "BGTG":{p:"Utama",i:[]},
  "BHAT":{p:"Pengembangan",i:[]},
  "BHIT":{p:"Pemantauan Khusus",i:[]},
  "BIKA":{p:"Pemantauan Khusus",i:[]},
  "BIKE":{p:"Pengembangan",i:["ISSI"]},
  "BIMA":{p:"Pemantauan Khusus",i:[]},
  "BINA":{p:"Utama",i:[]},
  "BINO":{p:"Pengembangan",i:["ISSI"]},
  "BIPI":{p:"Pengembangan",i:[]},
  "BIPP":{p:"Pemantauan Khusus",i:["ISSI"]},
  "BIRD":{p:"Utama",i:["ISSI"]},
  "BISI":{p:"Utama",i:["ISSI"]},
  "BJBR":{p:"Utama",i:[]},
  "BJTM":{p:"Utama",i:[]},
  "BKDP":{p:"Pemantauan Khusus",i:["ISSI"]},
  "BKSL":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "BKSW":{p:"Pengembangan",i:[]},
  "BLES":{p:"Pengembangan",i:["ISSI"]},
  "BLOG":{p:"Utama",i:["ISSI"]},
  "BLTA":{p:"Pemantauan Khusus",i:["ISSI"]},
  "BLTZ":{p:"Pemantauan Khusus",i:["ISSI"]},
  "BLUE":{p:"Pengembangan",i:["ISSI"]},
  "BMAS":{p:"Pengembangan",i:[]},
  "BMBL":{p:"Akselerasi",i:[]},
  "BMHS":{p:"Utama",i:["ISSI"]},
  "BMRI":{p:"Utama",i:["KOMPAS100", "LQ45"]},
  "BMSR":{p:"Pengembangan",i:["ISSI"]},
  "BMTR":{p:"Utama",i:["ISSI"]},
  "BNBA":{p:"Pengembangan",i:[]},
  "BNBR":{p:"Pemantauan Khusus",i:["ISSI"]},
  "BNGA":{p:"Utama",i:[]},
  "BNII":{p:"Utama",i:[]},
  "BNLI":{p:"Utama",i:[]},
  "BOAT":{p:"Pengembangan",i:["ISSI"]},
  "BOBA":{p:"Pengembangan",i:["ISSI"]},
  "BOGA":{p:"Pengembangan",i:["ISSI"]},
  "BOLA":{p:"Utama",i:["ISSI"]},
  "BOLT":{p:"Pengembangan",i:["ISSI"]},
  "BOSS":{p:"Pemantauan Khusus",i:[]},
  "BPFI":{p:"Pengembangan",i:[]},
  "BPII":{p:"Pengembangan",i:[]},
  "BPTR":{p:"Pengembangan",i:[]},
  "BRAM":{p:"Pengembangan",i:["ISSI"]},
  "BREN":{p:"Utama",i:["KOMPAS100", "LQ45"]},
  "BRIS":{p:"Utama",i:["BUMN", "ISSI", "KOMPAS100"]},
  "BRMS":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "BRNA":{p:"Pengembangan",i:["ISSI"]},
  "BRPT":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "BRRC":{p:"Pengembangan",i:["ISSI"]},
  "BSBK":{p:"Pengembangan",i:["ISSI"]},
  "BSDE":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "BSIM":{p:"Utama",i:[]},
  "BSML":{p:"Pengembangan",i:["ISSI"]},
  "BSSR":{p:"Pengembangan",i:["ISSI"]},
  "BSWD":{p:"Pemantauan Khusus",i:[]},
  "BTEK":{p:"Pemantauan Khusus",i:[]},
  "BTEL":{p:"Pemantauan Khusus",i:[]},
  "BTON":{p:"Pengembangan",i:[]},
  "BTPN":{p:"Utama",i:[]},
  "BTPS":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "BUAH":{p:"Pengembangan",i:["ISSI"]},
  "BUDI":{p:"Utama",i:[]},
  "BUKA":{p:"Ekonomi Baru",i:["KOMPAS100"]},
  "BUKK":{p:"Utama",i:["ISSI"]},
  "BULL":{p:"Pengembangan",i:["ISSI", "KOMPAS100"]},
  "BUMI":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "BUVA":{p:"Pengembangan",i:["ISSI", "KOMPAS100"]},
  "BVIC":{p:"Utama",i:[]},
  "BWPT":{p:"Utama",i:[]},
  "BYAN":{p:"Utama",i:["ISSI"]},
  "CAKK":{p:"Pengembangan",i:["ISSI"]},
  "CAMP":{p:"Pengembangan",i:["ISSI"]},
  "CANI":{p:"Pemantauan Khusus",i:["ISSI"]},
  "CARE":{p:"Pengembangan",i:["ISSI"]},
  "CARS":{p:"Utama",i:[]},
  "CASA":{p:"Pengembangan",i:[]},
  "CASH":{p:"Akselerasi",i:[]},
  "CASS":{p:"Utama",i:["ISSI"]},
  "CBDK":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "CBMF":{p:"Pemantauan Khusus",i:[]},
  "CBPE":{p:"Pengembangan",i:["ISSI"]},
  "CBRE":{p:"Pengembangan",i:["ISSI"]},
  "CBUT":{p:"Pengembangan",i:[]},
  "CCSI":{p:"Pengembangan",i:["ISSI"]},
  "CDIA":{p:"Pengembangan",i:[]},
  "CEKA":{p:"Pengembangan",i:["ISSI"]},
  "CENT":{p:"Pengembangan",i:[]},
  "CFIN":{p:"Utama",i:[]},
  "CGAS":{p:"Pengembangan",i:["ISSI"]},
  "CHEK":{p:"Pengembangan",i:["ISSI"]},
  "CHEM":{p:"Pengembangan",i:["ISSI"]},
  "CHIP":{p:"Akselerasi",i:[]},
  "CINT":{p:"Pengembangan",i:["ISSI"]},
  "CITA":{p:"Utama",i:["ISSI"]},
  "CITY":{p:"Pengembangan",i:["ISSI"]},
  "CLAY":{p:"Pengembangan",i:[]},
  "CLEO":{p:"Utama",i:["ISSI"]},
  "CLPI":{p:"Pengembangan",i:["ISSI"]},
  "CMNP":{p:"Utama",i:["ISSI"]},
  "CMNT":{p:"Pengembangan",i:[]},
  "CMPP":{p:"Pemantauan Khusus",i:["ISSI"]},
  "CMRY":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "CNKO":{p:"Pemantauan Khusus",i:["ISSI"]},
  "CNMA":{p:"Pengembangan",i:["ISSI"]},
  "CNTX":{p:"Pemantauan Khusus",i:[]},
  "COAL":{p:"Pengembangan",i:["ISSI"]},
  "COCO":{p:"Pemantauan Khusus",i:[]},
  "COIN":{p:"Pengembangan",i:[]},
  "COWL":{p:"Pemantauan Khusus",i:[]},
  "CPIN":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "CPRI":{p:"Pemantauan Khusus",i:[]},
  "CPRO":{p:"Pengembangan",i:["ISSI"]},
  "CRAB":{p:"Pengembangan",i:["ISSI"]},
  "CRSN":{p:"Pengembangan",i:["ISSI"]},
  "CSAP":{p:"Pengembangan",i:["ISSI"]},
  "CSIS":{p:"Pengembangan",i:["ISSI"]},
  "CSMI":{p:"Pengembangan",i:["ISSI"]},
  "CSRA":{p:"Utama",i:["ISSI"]},
  "CTBN":{p:"Pengembangan",i:["ISSI"]},
  "CTRA":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "CTTH":{p:"Pengembangan",i:[]},
  "CUAN":{p:"Utama",i:["KOMPAS100"]},
  "CYBR":{p:"Pengembangan",i:["ISSI"]},
  "DAAZ":{p:"Utama",i:["ISSI"]},
  "DADA":{p:"Pengembangan",i:["ISSI"]},
  "DART":{p:"Pengembangan",i:[]},
  "DATA":{p:"Pengembangan",i:["ISSI"]},
  "DAYA":{p:"Pengembangan",i:["ISSI"]},
  "DCII":{p:"Pengembangan",i:["ISSI"]},
  "DEAL":{p:"Pemantauan Khusus",i:[]},
  "DEFI":{p:"Pengembangan",i:["ISSI"]},
  "DEPO":{p:"Pengembangan",i:["ISSI"]},
  "DEWA":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "DEWI":{p:"Pengembangan",i:["ISSI"]},
  "DFAM":{p:"Pengembangan",i:[]},
  "DGIK":{p:"Pengembangan",i:["ISSI"]},
  "DGNS":{p:"Pengembangan",i:["ISSI"]},
  "DGWG":{p:"Utama",i:["ISSI"]},
  "DIGI":{p:"Pemantauan Khusus",i:[]},
  "DILD":{p:"Utama",i:["ISSI"]},
  "DIVA":{p:"Pengembangan",i:["ISSI"]},
  "DKFT":{p:"Pengembangan",i:["ISSI"]},
  "DKHH":{p:"Pengembangan",i:["ISSI"]},
  "DLTA":{p:"Utama",i:[]},
  "DMAS":{p:"Utama",i:["ISSI"]},
  "DMMX":{p:"Pengembangan",i:["ISSI"]},
  "DMND":{p:"Pengembangan",i:["ISSI"]},
  "DNAR":{p:"Pengembangan",i:[]},
  "DNET":{p:"Utama",i:[]},
  "DOID":{p:"Utama",i:[]},
  "DOOH":{p:"Pengembangan",i:["ISSI"]},
  "DOSS":{p:"Pengembangan",i:["ISSI"]},
  "DPNS":{p:"Pengembangan",i:[]},
  "DPUM":{p:"Pemantauan Khusus",i:[]},
  "DRMA":{p:"Utama",i:["ISSI"]},
  "DSFI":{p:"Pengembangan",i:["ISSI"]},
  "DSNG":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "DSSA":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "DUCK":{p:"Pemantauan Khusus",i:[]},
  "DUTI":{p:"Pengembangan",i:["ISSI"]},
  "DVLA":{p:"Pengembangan",i:["ISSI"]},
  "DWGL":{p:"Pengembangan",i:["ISSI"]},
  "DYAN":{p:"Pengembangan",i:["ISSI"]},
  "EAST":{p:"Pengembangan",i:["ISSI"]},
  "ECII":{p:"Pengembangan",i:["ISSI"]},
  "EDGE":{p:"Pengembangan",i:["ISSI"]},
  "EKAD":{p:"Pengembangan",i:["ISSI"]},
  "ELIT":{p:"Pengembangan",i:["ISSI"]},
  "ELPI":{p:"Utama",i:["ISSI"]},
  "ELSA":{p:"Utama",i:["BUMN", "ISSI", "KOMPAS100"]},
  "ELTY":{p:"Pemantauan Khusus",i:["ISSI"]},
  "EMAS":{p:"Pengembangan",i:[]},
  "EMDE":{p:"Pengembangan",i:["ISSI"]},
  "EMTK":{p:"Utama",i:["KOMPAS100", "LQ45"]},
  "ENAK":{p:"Pengembangan",i:["ISSI"]},
  "ENRG":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "ENVY":{p:"Pemantauan Khusus",i:[]},
  "ENZO":{p:"Pemantauan Khusus",i:[]},
  "EPAC":{p:"Pemantauan Khusus",i:["ISSI"]},
  "EPMT":{p:"Pengembangan",i:["ISSI"]},
  "ERAA":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "ERAL":{p:"Utama",i:["ISSI"]},
  "ERTX":{p:"Pengembangan",i:[]},
  "ESIP":{p:"Pengembangan",i:["ISSI"]},
  "ESSA":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "ESTA":{p:"Pengembangan",i:["ISSI"]},
  "ESTI":{p:"Pengembangan",i:[]},
  "ETWA":{p:"Pemantauan Khusus",i:[]},
  "EURO":{p:"Akselerasi",i:[]},
  "EXCL":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "FAPA":{p:"Pengembangan",i:[]},
  "FAST":{p:"Pengembangan",i:["ISSI"]},
  "FASW":{p:"Pemantauan Khusus",i:["ISSI"]},
  "FILM":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "FIMP":{p:"Pemantauan Khusus",i:[]},
  "FIRE":{p:"Pengembangan",i:["ISSI"]},
  "FISH":{p:"Pengembangan",i:["ISSI"]},
  "FITT":{p:"Pengembangan",i:["ISSI"]},
  "FLMC":{p:"Akselerasi",i:[]},
  "FMII":{p:"Pengembangan",i:["ISSI"]},
  "FOLK":{p:"Pengembangan",i:["ISSI"]},
  "FOOD":{p:"Pemantauan Khusus",i:["ISSI"]},
  "FORE":{p:"Pengembangan",i:["ISSI"]},
  "FORU":{p:"Pengembangan",i:[]},
  "FPNI":{p:"Pengembangan",i:["ISSI"]},
  "FUJI":{p:"Pengembangan",i:[]},
  "FUTR":{p:"Pengembangan",i:["ISSI"]},
  "FWCT":{p:"Pengembangan",i:["ISSI"]},
  "GAMA":{p:"Pemantauan Khusus",i:[]},
  "GDST":{p:"Pengembangan",i:["ISSI"]},
  "GDYR":{p:"Pengembangan",i:["ISSI"]},
  "GEMA":{p:"Pengembangan",i:["ISSI"]},
  "GEMS":{p:"Utama",i:["ISSI"]},
  "GGRM":{p:"Utama",i:[]},
  "GGRP":{p:"Pengembangan",i:["ISSI"]},
  "GHON":{p:"Pengembangan",i:["ISSI"]},
  "GIAA":{p:"Pemantauan Khusus",i:["ISSI"]},
  "GJTL":{p:"Utama",i:["ISSI"]},
  "GLOB":{p:"Pemantauan Khusus",i:[]},
  "GLVA":{p:"Pengembangan",i:["ISSI"]},
  "GMFI":{p:"Pemantauan Khusus",i:[]},
  "GMTD":{p:"Pengembangan",i:["ISSI"]},
  "GOLD":{p:"Pengembangan",i:["ISSI"]},
  "GOLF":{p:"Utama",i:["ISSI"]},
  "GOLL":{p:"Pemantauan Khusus",i:[]},
  "GOOD":{p:"Utama",i:["ISSI"]},
  "GOTO":{p:"Ekonomi Baru",i:["KOMPAS100", "LQ45"]},
  "GPRA":{p:"Pengembangan",i:["ISSI"]},
  "GPSO":{p:"Pengembangan",i:["ISSI"]},
  "GRIA":{p:"Pengembangan",i:["ISSI"]},
  "GRPH":{p:"Pengembangan",i:["ISSI"]},
  "GRPM":{p:"Akselerasi",i:[]},
  "GSMF":{p:"Pengembangan",i:[]},
  "GTBO":{p:"Pengembangan",i:["ISSI"]},
  "GTRA":{p:"Pengembangan",i:["ISSI"]},
  "GTSI":{p:"Utama",i:["ISSI"]},
  "GULA":{p:"Pengembangan",i:["ISSI"]},
  "GUNA":{p:"Pengembangan",i:["ISSI"]},
  "GWSA":{p:"Utama",i:["ISSI"]},
  "GZCO":{p:"Pengembangan",i:["ISSI"]},
  "HADE":{p:"Pemantauan Khusus",i:["ISSI"]},
  "HAIS":{p:"Pengembangan",i:["ISSI"]},
  "HAJJ":{p:"Akselerasi",i:[]},
  "HALO":{p:"Pengembangan",i:["ISSI"]},
  "HATM":{p:"Utama",i:["ISSI"]},
  "HBAT":{p:"Akselerasi",i:[]},
  "HDFA":{p:"Pengembangan",i:[]},
  "HDIT":{p:"Pengembangan",i:["ISSI"]},
  "HEAL":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "HELI":{p:"Pengembangan",i:[]},
  "HERO":{p:"Pengembangan",i:["ISSI"]},
  "HEXA":{p:"Utama",i:["ISSI"]},
  "HGII":{p:"Pengembangan",i:["ISSI"]},
  "HILL":{p:"Utama",i:[]},
  "HITS":{p:"Pemantauan Khusus",i:["ISSI"]},
  "HKMU":{p:"Pemantauan Khusus",i:[]},
  "HMSP":{p:"Utama",i:["KOMPAS100"]},
  "HOKI":{p:"Pengembangan",i:["ISSI"]},
  "HOME":{p:"Pemantauan Khusus",i:[]},
  "HOMI":{p:"Pengembangan",i:["ISSI"]},
  "HOPE":{p:"Pengembangan",i:["ISSI"]},
  "HOTL":{p:"Pemantauan Khusus",i:[]},
  "HRME":{p:"Pemantauan Khusus",i:["ISSI"]},
  "HRTA":{p:"Utama",i:["KOMPAS100"]},
  "HRUM":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "HUMI":{p:"Pengembangan",i:["ISSI"]},
  "HYGN":{p:"Pengembangan",i:["ISSI"]},
  "IATA":{p:"Pengembangan",i:["ISSI"]},
  "IBFN":{p:"Pemantauan Khusus",i:[]},
  "IBOS":{p:"Pemantauan Khusus",i:[]},
  "IBST":{p:"Pemantauan Khusus",i:["ISSI"]},
  "ICBP":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "ICON":{p:"Pemantauan Khusus",i:["ISSI"]},
  "IDEA":{p:"Akselerasi",i:[]},
  "IDPR":{p:"Pengembangan",i:["ISSI"]},
  "IFII":{p:"Pengembangan",i:["ISSI"]},
  "IFSH":{p:"Pengembangan",i:["ISSI"]},
  "IGAR":{p:"Pengembangan",i:["ISSI"]},
  "IIKP":{p:"Pemantauan Khusus",i:["ISSI"]},
  "IKAI":{p:"Pemantauan Khusus",i:["ISSI"]},
  "IKAN":{p:"Pengembangan",i:["ISSI"]},
  "IKBI":{p:"Pengembangan",i:["ISSI"]},
  "IKPM":{p:"Pengembangan",i:["ISSI"]},
  "IMAS":{p:"Utama",i:[]},
  "IMJS":{p:"Pengembangan",i:[]},
  "IMPC":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "INAF":{p:"Pemantauan Khusus",i:[]},
  "INAI":{p:"Pengembangan",i:[]},
  "INCF":{p:"Pemantauan Khusus",i:[]},
  "INCI":{p:"Pengembangan",i:["ISSI"]},
  "INCO":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "INDF":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "INDO":{p:"Pengembangan",i:[]},
  "INDR":{p:"Pengembangan",i:["ISSI"]},
  "INDS":{p:"Pemantauan Khusus",i:["ISSI"]},
  "INDX":{p:"Pengembangan",i:["ISSI"]},
  "INDY":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "INET":{p:"Pengembangan",i:["ISSI", "KOMPAS100"]},
  "INKP":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "INOV":{p:"Pengembangan",i:[]},
  "INPC":{p:"Utama",i:[]},
  "INPP":{p:"Pengembangan",i:["ISSI"]},
  "INPS":{p:"Pemantauan Khusus",i:[]},
  "INRU":{p:"Pengembangan",i:[]},
  "INTA":{p:"Pemantauan Khusus",i:[]},
  "INTD":{p:"Pengembangan",i:["ISSI"]},
  "INTP":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "IOTF":{p:"Pengembangan",i:["ISSI"]},
  "IPAC":{p:"Akselerasi",i:[]},
  "IPCC":{p:"Utama",i:["BUMN", "ISSI"]},
  "IPCM":{p:"Utama",i:["ISSI"]},
  "IPOL":{p:"Pengembangan",i:["ISSI"]},
  "IPPE":{p:"Pemantauan Khusus",i:[]},
  "IPTV":{p:"Pemantauan Khusus",i:["ISSI"]},
  "IRRA":{p:"Pengembangan",i:["ISSI"]},
  "IRSX":{p:"Pengembangan",i:["ISSI"]},
  "ISAP":{p:"Akselerasi",i:[]},
  "ISAT":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "ISEA":{p:"Pengembangan",i:[]},
  "ISSP":{p:"Utama",i:["ISSI"]},
  "ITIC":{p:"Pengembangan",i:[]},
  "ITMA":{p:"Pengembangan",i:["ISSI"]},
  "ITMG":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "JARR":{p:"Utama",i:[]},
  "JAST":{p:"Pengembangan",i:["ISSI"]},
  "JATI":{p:"Pengembangan",i:["ISSI"]},
  "JAWA":{p:"Pengembangan",i:["ISSI"]},
  "JAYA":{p:"Pengembangan",i:["ISSI"]},
  "JECC":{p:"Pengembangan",i:["ISSI"]},
  "JGLE":{p:"Pemantauan Khusus",i:["ISSI"]},
  "JIHD":{p:"Pengembangan",i:["ISSI"]},
  "JKON":{p:"Utama",i:["BUMN", "ISSI"]},
  "JMAS":{p:"Pengembangan",i:["ISSI"]},
  "JPFA":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "JRPT":{p:"Utama",i:["BUMN", "ISSI"]},
  "JSKY":{p:"Pemantauan Khusus",i:[]},
  "JSMR":{p:"Utama",i:["BUMN", "ISSI", "KOMPAS100"]},
  "JSPT":{p:"Pengembangan",i:["ISSI"]},
  "JTPE":{p:"Utama",i:["ISSI"]},
  "KAEF":{p:"Pengembangan",i:[]},
  "KAQI":{p:"Pengembangan",i:["ISSI"]},
  "KARW":{p:"Pemantauan Khusus",i:["ISSI"]},
  "KAYU":{p:"Pemantauan Khusus",i:[]},
  "KBAG":{p:"Pemantauan Khusus",i:["ISSI"]},
  "KBLI":{p:"Utama",i:["ISSI"]},
  "KBLM":{p:"Pengembangan",i:["ISSI"]},
  "KBLV":{p:"Pengembangan",i:[]},
  "KBRI":{p:"Pemantauan Khusus",i:[]},
  "KDSI":{p:"Pengembangan",i:["ISSI"]},
  "KDTN":{p:"Pengembangan",i:["ISSI"]},
  "KEEN":{p:"Utama",i:["ISSI"]},
  "KEJU":{p:"Utama",i:["ISSI"]},
  "KETR":{p:"Pengembangan",i:["ISSI"]},
  "KIAS":{p:"Pemantauan Khusus",i:["ISSI"]},
  "KICI":{p:"Pengembangan",i:["ISSI"]},
  "KIJA":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "KING":{p:"Akselerasi",i:[]},
  "KINO":{p:"Pengembangan",i:["ISSI"]},
  "KIOS":{p:"Pengembangan",i:["ISSI"]},
  "KJEN":{p:"Pengembangan",i:["ISSI"]},
  "KKES":{p:"Pemantauan Khusus",i:["ISSI"]},
  "KKGI":{p:"Utama",i:["ISSI"]},
  "KLAS":{p:"Pengembangan",i:["ISSI"]},
  "KLBF":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "KLIN":{p:"Akselerasi",i:[]},
  "KMDS":{p:"Pengembangan",i:["ISSI"]},
  "KMTR":{p:"Pengembangan",i:[]},
  "KOBX":{p:"Pengembangan",i:["ISSI"]},
  "KOCI":{p:"Pengembangan",i:["ISSI"]},
  "KOIN":{p:"Pemantauan Khusus",i:["ISSI"]},
  "KOKA":{p:"Pengembangan",i:["ISSI"]},
  "KONI":{p:"Pengembangan",i:["ISSI"]},
  "KOPI":{p:"Pengembangan",i:["ISSI"]},
  "KOTA":{p:"Pemantauan Khusus",i:["ISSI"]},
  "KPIG":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "KRAS":{p:"Pengembangan",i:[]},
  "KREN":{p:"Pemantauan Khusus",i:["ISSI"]},
  "KRYA":{p:"Pengembangan",i:["ISSI"]},
  "KSIX":{p:"Pengembangan",i:["ISSI"]},
  "KUAS":{p:"Pengembangan",i:["ISSI"]},
  "LABA":{p:"Pengembangan",i:["ISSI"]},
  "LABS":{p:"Pengembangan",i:["ISSI"]},
  "LAJU":{p:"Pengembangan",i:["ISSI"]},
  "LAND":{p:"Pemantauan Khusus",i:["ISSI"]},
  "LAPD":{p:"Pengembangan",i:[]},
  "LCGP":{p:"Pemantauan Khusus",i:[]},
  "LCKM":{p:"Pengembangan",i:["ISSI"]},
  "LEAD":{p:"Pengembangan",i:[]},
  "LFLO":{p:"Akselerasi",i:[]},
  "LIFE":{p:"Pengembangan",i:[]},
  "LINK":{p:"Pengembangan",i:[]},
  "LION":{p:"Pengembangan",i:["ISSI"]},
  "LIVE":{p:"Pengembangan",i:["ISSI"]},
  "LMAS":{p:"Pemantauan Khusus",i:[]},
  "LMAX":{p:"Akselerasi",i:[]},
  "LMPI":{p:"Pengembangan",i:["ISSI"]},
  "LMSH":{p:"Pemantauan Khusus",i:["ISSI"]},
  "LOPI":{p:"Akselerasi",i:[]},
  "LPCK":{p:"Pengembangan",i:["ISSI"]},
  "LPGI":{p:"Pengembangan",i:[]},
  "LPIN":{p:"Pengembangan",i:["ISSI"]},
  "LPKR":{p:"Utama",i:["ISSI"]},
  "LPLI":{p:"Pengembangan",i:["ISSI"]},
  "LPPF":{p:"Utama",i:["ISSI"]},
  "LPPS":{p:"Pengembangan",i:[]},
  "LRNA":{p:"Pengembangan",i:["ISSI"]},
  "LSIP":{p:"Utama",i:["ISSI"]},
  "LTLS":{p:"Utama",i:["ISSI"]},
  "LUCK":{p:"Pengembangan",i:["ISSI"]},
  "LUCY":{p:"Akselerasi",i:[]},
  "MABA":{p:"Pemantauan Khusus",i:[]},
  "MAGP":{p:"Pemantauan Khusus",i:[]},
  "MAHA":{p:"Utama",i:["ISSI"]},
  "MAIN":{p:"Utama",i:["ISSI"]},
  "MANG":{p:"Akselerasi",i:[]},
  "MAPA":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "MAPB":{p:"Pengembangan",i:["ISSI"]},
  "MAPI":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "MARI":{p:"Pemantauan Khusus",i:[]},
  "MARK":{p:"Utama",i:["ISSI"]},
  "MASB":{p:"Pengembangan",i:[]},
  "MAXI":{p:"Pengembangan",i:["ISSI"]},
  "MAYA":{p:"Utama",i:[]},
  "MBAP":{p:"Pengembangan",i:["ISSI"]},
  "MBMA":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "MBSS":{p:"Utama",i:[]},
  "MBTO":{p:"Pengembangan",i:["ISSI"]},
  "MCAS":{p:"Utama",i:["ISSI"]},
  "MCOL":{p:"Utama",i:["ISSI"]},
  "MCOR":{p:"Utama",i:[]},
  "MDIA":{p:"Pemantauan Khusus",i:[]},
  "MDIY":{p:"Utama",i:["ISSI"]},
  "MDKA":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "MDKI":{p:"Pengembangan",i:["ISSI"]},
  "MDLA":{p:"Utama",i:["ISSI"]},
  "MDLN":{p:"Pengembangan",i:[]},
  "MDRN":{p:"Pemantauan Khusus",i:[]},
  "MEDC":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "MEDS":{p:"Pengembangan",i:["ISSI"]},
  "MEGA":{p:"Utama",i:[]},
  "MEJA":{p:"Akselerasi",i:[]},
  "MENN":{p:"Akselerasi",i:[]},
  "MERI":{p:"Pengembangan",i:["ISSI"]},
  "MERK":{p:"Pengembangan",i:["ISSI"]},
  "META":{p:"Pemantauan Khusus",i:["ISSI"]},
  "MFMI":{p:"Pemantauan Khusus",i:["ISSI"]},
  "MGLV":{p:"Akselerasi",i:[]},
  "MGNA":{p:"Pengembangan",i:["ISSI"]},
  "MGRO":{p:"Pengembangan",i:[]},
  "MHKI":{p:"Pengembangan",i:["ISSI"]},
  "MICE":{p:"Pengembangan",i:["ISSI"]},
  "MIDI":{p:"Utama",i:["ISSI"]},
  "MIKA":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "MINA":{p:"Pengembangan",i:["ISSI"]},
  "MINE":{p:"Utama",i:["ISSI"]},
  "MIRA":{p:"Pemantauan Khusus",i:["ISSI"]},
  "MITI":{p:"Pengembangan",i:["ISSI"]},
  "MKAP":{p:"Pengembangan",i:["ISSI"]},
  "MKNT":{p:"Pemantauan Khusus",i:[]},
  "MKPI":{p:"Pengembangan",i:["ISSI"]},
  "MKTR":{p:"Utama",i:["ISSI"]},
  "MLBI":{p:"Utama",i:[]},
  "MLIA":{p:"Utama",i:["ISSI"]},
  "MLPL":{p:"Utama",i:["ISSI"]},
  "MLPT":{p:"Pengembangan",i:["ISSI"]},
  "MMIX":{p:"Pengembangan",i:["ISSI"]},
  "MMLP":{p:"Utama",i:["ISSI"]},
  "MNCN":{p:"Utama",i:["ISSI"]},
  "MOLI":{p:"Pengembangan",i:[]},
  "MORA":{p:"Utama",i:["ISSI"]},
  "MPIX":{p:"Pengembangan",i:["ISSI"]},
  "MPMX":{p:"Utama",i:["ISSI"]},
  "MPOW":{p:"Pengembangan",i:["ISSI"]},
  "MPPA":{p:"Pengembangan",i:["ISSI"]},
  "MPRO":{p:"Pengembangan",i:["ISSI"]},
  "MPXL":{p:"Pengembangan",i:[]},
  "MRAT":{p:"Pengembangan",i:["ISSI"]},
  "MREI":{p:"Utama",i:[]},
  "MSIE":{p:"Akselerasi",i:[]},
  "MSIN":{p:"Utama",i:["ISSI"]},
  "MSJA":{p:"Pengembangan",i:["ISSI"]},
  "MSKY":{p:"Pengembangan",i:["ISSI"]},
  "MSTI":{p:"Utama",i:["ISSI"]},
  "MTDL":{p:"Utama",i:["ISSI"]},
  "MTEL":{p:"Utama",i:["BUMN", "ISSI", "KOMPAS100"]},
  "MTFN":{p:"Pemantauan Khusus",i:["ISSI"]},
  "MTLA":{p:"Utama",i:["ISSI"]},
  "MTMH":{p:"Utama",i:["ISSI"]},
  "MTPS":{p:"Pemantauan Khusus",i:["ISSI"]},
  "MTRA":{p:"Pemantauan Khusus",i:[]},
  "MTSM":{p:"Pemantauan Khusus",i:["ISSI"]},
  "MTWI":{p:"Pengembangan",i:[]},
  "MUTU":{p:"Pengembangan",i:["ISSI"]},
  "MYOH":{p:"Pengembangan",i:["ISSI"]},
  "MYOR":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "MYTX":{p:"Pemantauan Khusus",i:[]},
  "NAIK":{p:"Pengembangan",i:["ISSI"]},
  "NANO":{p:"Akselerasi",i:[]},
  "NASA":{p:"Pemantauan Khusus",i:["ISSI"]},
  "NASI":{p:"Pengembangan",i:["ISSI"]},
  "NATO":{p:"Pengembangan",i:[]},
  "NAYZ":{p:"Akselerasi",i:[]},
  "NCKL":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "NELY":{p:"Pengembangan",i:["ISSI"]},
  "NEST":{p:"Pengembangan",i:["ISSI"]},
  "NETV":{p:"Pengembangan",i:["ISSI"]},
  "NFCX":{p:"Pengembangan",i:["ISSI"]},
  "NICE":{p:"Pengembangan",i:["ISSI"]},
  "NICK":{p:"Pengembangan",i:[]},
  "NICL":{p:"Pengembangan",i:["ISSI"]},
  "NIKL":{p:"Pengembangan",i:["ISSI"]},
  "NINE":{p:"Akselerasi",i:[]},
  "NIRO":{p:"Pengembangan",i:[]},
  "NISP":{p:"Utama",i:[]},
  "NOBU":{p:"Pengembangan",i:[]},
  "NPGF":{p:"Pengembangan",i:["ISSI"]},
  "NRCA":{p:"Pengembangan",i:["ISSI"]},
  "NSSS":{p:"Pengembangan",i:[]},
  "NTBK":{p:"Pengembangan",i:["ISSI"]},
  "NUSA":{p:"Pemantauan Khusus",i:[]},
  "NZIA":{p:"Pengembangan",i:["ISSI"]},
  "OASA":{p:"Pengembangan",i:["ISSI"]},
  "OBAT":{p:"Pengembangan",i:["ISSI"]},
  "OBMD":{p:"Pengembangan",i:["ISSI"]},
  "OCAP":{p:"Pemantauan Khusus",i:[]},
  "OILS":{p:"Pengembangan",i:["ISSI"]},
  "OKAS":{p:"Pengembangan",i:["ISSI"]},
  "OLIV":{p:"Akselerasi",i:[]},
  "OMED":{p:"Utama",i:["ISSI"]},
  "OMRE":{p:"Pemantauan Khusus",i:["ISSI"]},
  "OPMS":{p:"Pengembangan",i:[]},
  "PACK":{p:"Akselerasi",i:[]},
  "PADA":{p:"Pengembangan",i:["ISSI"]},
  "PADI":{p:"Pemantauan Khusus",i:[]},
  "PALM":{p:"Pengembangan",i:["ISSI"]},
  "PAMG":{p:"Pengembangan",i:["ISSI"]},
  "PANI":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "PANR":{p:"Utama",i:["ISSI"]},
  "PANS":{p:"Utama",i:[]},
  "PART":{p:"Pengembangan",i:["ISSI"]},
  "PBID":{p:"Utama",i:["ISSI"]},
  "PBRX":{p:"Pemantauan Khusus",i:[]},
  "PBSA":{p:"Pengembangan",i:["ISSI"]},
  "PCAR":{p:"Pemantauan Khusus",i:["ISSI"]},
  "PDES":{p:"Pengembangan",i:["ISSI"]},
  "PDPP":{p:"Pengembangan",i:["ISSI"]},
  "PEGE":{p:"Pengembangan",i:[]},
  "PEHA":{p:"Pengembangan",i:["ISSI"]},
  "PEVE":{p:"Pengembangan",i:["ISSI"]},
  "PGAS":{p:"Utama",i:["BUMN", "ISSI", "KOMPAS100", "LQ45"]},
  "PGEO":{p:"Utama",i:["BUMN", "ISSI", "KOMPAS100", "LQ45"]},
  "PGJO":{p:"Akselerasi",i:[]},
  "PGLI":{p:"Pengembangan",i:["ISSI"]},
  "PGUN":{p:"Pengembangan",i:["ISSI"]},
  "PICO":{p:"Pengembangan",i:["ISSI"]},
  "PIPA":{p:"Pengembangan",i:["ISSI"]},
  "PJAA":{p:"Pengembangan",i:["ISSI"]},
  "PJHB":{p:"Pengembangan",i:["ISSI"]},
  "PKPK":{p:"Pengembangan",i:["ISSI"]},
  "PLAN":{p:"Akselerasi",i:[]},
  "PLAS":{p:"Pemantauan Khusus",i:[]},
  "PLIN":{p:"Pemantauan Khusus",i:["ISSI"]},
  "PMJS":{p:"Pengembangan",i:["ISSI"]},
  "PMMP":{p:"Pemantauan Khusus",i:[]},
  "PMUI":{p:"Pengembangan",i:["ISSI"]},
  "PNBN":{p:"Utama",i:[]},
  "PNBS":{p:"Pengembangan",i:["ISSI"]},
  "PNGO":{p:"Utama",i:["ISSI"]},
  "PNIN":{p:"Utama",i:[]},
  "PNLF":{p:"Utama",i:["KOMPAS100"]},
  "PNSE":{p:"Pengembangan",i:["ISSI"]},
  "POLA":{p:"Pemantauan Khusus",i:[]},
  "POLI":{p:"Pemantauan Khusus",i:["ISSI"]},
  "POLL":{p:"Pemantauan Khusus",i:[]},
  "POLU":{p:"Pengembangan",i:["ISSI"]},
  "POLY":{p:"Pemantauan Khusus",i:[]},
  "POOL":{p:"Pemantauan Khusus",i:[]},
  "PORT":{p:"Pengembangan",i:["ISSI"]},
  "POSA":{p:"Pemantauan Khusus",i:[]},
  "POWR":{p:"Utama",i:["ISSI"]},
  "PPGL":{p:"Pemantauan Khusus",i:[]},
  "PPRE":{p:"Pengembangan",i:["ISSI"]},
  "PPRI":{p:"Pengembangan",i:["ISSI"]},
  "PPRO":{p:"Pemantauan Khusus",i:["ISSI"]},
  "PRAY":{p:"Pengembangan",i:["ISSI"]},
  "PRDA":{p:"Utama",i:["ISSI"]},
  "PRIM":{p:"Pengembangan",i:["ISSI"]},
  "PSAB":{p:"Pengembangan",i:["ISSI", "KOMPAS100"]},
  "PSAT":{p:"Utama",i:["ISSI"]},
  "PSDN":{p:"Pengembangan",i:["ISSI"]},
  "PSGO":{p:"Utama",i:["ISSI"]},
  "PSKT":{p:"Pengembangan",i:["ISSI"]},
  "PSSI":{p:"Utama",i:["ISSI"]},
  "PTBA":{p:"Utama",i:["BUMN", "ISSI", "KOMPAS100", "LQ45"]},
  "PTDU":{p:"Pemantauan Khusus",i:[]},
  "PTIS":{p:"Pengembangan",i:["ISSI"]},
  "PTMP":{p:"Pengembangan",i:["ISSI"]},
  "PTMR":{p:"Pemantauan Khusus",i:["ISSI"]},
  "PTPP":{p:"Utama",i:["BUMN", "ISSI"]},
  "PTPS":{p:"Pengembangan",i:["ISSI"]},
  "PTPW":{p:"Pengembangan",i:["ISSI"]},
  "PTRO":{p:"Utama",i:["KOMPAS100"]},
  "PTSN":{p:"Pengembangan",i:["ISSI"]},
  "PTSP":{p:"Pengembangan",i:["ISSI"]},
  "PUDP":{p:"Pengembangan",i:[]},
  "PURA":{p:"Pemantauan Khusus",i:["ISSI"]},
  "PURE":{p:"Pemantauan Khusus",i:[]},
  "PURI":{p:"Pengembangan",i:["ISSI"]},
  "PWON":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "PYFA":{p:"Pengembangan",i:[]},
  "PZZA":{p:"Pengembangan",i:["ISSI"]},
  "RAAM":{p:"Utama",i:["ISSI"]},
  "RAFI":{p:"Pemantauan Khusus",i:["ISSI"]},
  "RAJA":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "RALS":{p:"Utama",i:["ISSI"]},
  "RANC":{p:"Pengembangan",i:["ISSI"]},
  "RATU":{p:"Pengembangan",i:["ISSI", "KOMPAS100"]},
  "RBMS":{p:"Pemantauan Khusus",i:["ISSI"]},
  "RCCC":{p:"Akselerasi",i:[]},
  "RDTX":{p:"Pengembangan",i:["ISSI"]},
  "REAL":{p:"Pengembangan",i:[]},
  "RELF":{p:"Akselerasi",i:[]},
  "RELI":{p:"Pengembangan",i:[]},
  "RGAS":{p:"Pengembangan",i:["ISSI"]},
  "RICY":{p:"Pemantauan Khusus",i:[]},
  "RIGS":{p:"Pengembangan",i:["ISSI"]},
  "RIMO":{p:"Pemantauan Khusus",i:[]},
  "RISE":{p:"Pengembangan",i:["ISSI"]},
  "RLCO":{p:"Pengembangan",i:[]},
  "RMKE":{p:"Utama",i:["ISSI"]},
  "RMKO":{p:"Pengembangan",i:["ISSI"]},
  "ROCK":{p:"Pemantauan Khusus",i:["ISSI"]},
  "RODA":{p:"Pemantauan Khusus",i:["ISSI"]},
  "RONY":{p:"Pengembangan",i:["ISSI"]},
  "ROTI":{p:"Pengembangan",i:["ISSI"]},
  "RSCH":{p:"Pengembangan",i:[]},
  "RSGK":{p:"Pemantauan Khusus",i:["ISSI"]},
  "RUIS":{p:"Pengembangan",i:["ISSI"]},
  "RUNS":{p:"Akselerasi",i:[]},
  "SAFE":{p:"Pengembangan",i:["ISSI"]},
  "SAGE":{p:"Pemantauan Khusus",i:["ISSI"]},
  "SAME":{p:"Utama",i:["ISSI"]},
  "SAMF":{p:"Utama",i:["ISSI"]},
  "SAPX":{p:"Pengembangan",i:["ISSI"]},
  "SATU":{p:"Pengembangan",i:["ISSI"]},
  "SBAT":{p:"Pemantauan Khusus",i:[]},
  "SBMA":{p:"Pengembangan",i:["ISSI"]},
  "SCCO":{p:"Pengembangan",i:["ISSI"]},
  "SCMA":{p:"Utama",i:["KOMPAS100", "LQ45"]},
  "SCNP":{p:"Pengembangan",i:["ISSI"]},
  "SCPI":{p:"Pemantauan Khusus",i:["ISSI"]},
  "SDMU":{p:"Pengembangan",i:[]},
  "SDPC":{p:"Pengembangan",i:[]},
  "SDRA":{p:"Pengembangan",i:[]},
  "SEMA":{p:"Pengembangan",i:["ISSI"]},
  "SFAN":{p:"Pengembangan",i:[]},
  "SGER":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "SGRO":{p:"Utama",i:["ISSI"]},
  "SHID":{p:"Pengembangan",i:["ISSI"]},
  "SHIP":{p:"Utama",i:["ISSI"]},
  "SICO":{p:"Pengembangan",i:["ISSI"]},
  "SIDO":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "SILO":{p:"Utama",i:["ISSI"]},
  "SIMA":{p:"Pemantauan Khusus",i:[]},
  "SIMP":{p:"Utama",i:["ISSI"]},
  "SINI":{p:"Pemantauan Khusus",i:[]},
  "SIPD":{p:"Pemantauan Khusus",i:["ISSI"]},
  "SKBM":{p:"Pengembangan",i:["ISSI"]},
  "SKLT":{p:"Pengembangan",i:["ISSI"]},
  "SKRN":{p:"Utama",i:["ISSI"]},
  "SKYB":{p:"Pemantauan Khusus",i:[]},
  "SLIS":{p:"Pengembangan",i:["ISSI"]},
  "SMAR":{p:"Utama",i:["ISSI"]},
  "SMBR":{p:"Utama",i:["BUMN", "ISSI"]},
  "SMCB":{p:"Pemantauan Khusus",i:["ISSI"]},
  "SMDM":{p:"Pengembangan",i:["ISSI"]},
  "SMDR":{p:"Utama",i:["ISSI"]},
  "SMGA":{p:"Pengembangan",i:["ISSI"]},
  "SMGR":{p:"Utama",i:["BUMN", "ISSI", "KOMPAS100", "LQ45"]},
  "SMIL":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "SMKL":{p:"Pengembangan",i:["ISSI"]},
  "SMKM":{p:"Akselerasi",i:[]},
  "SMLE":{p:"Pengembangan",i:["ISSI"]},
  "SMMA":{p:"Utama",i:[]},
  "SMMT":{p:"Pengembangan",i:["ISSI"]},
  "SMRA":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "SMRU":{p:"Pemantauan Khusus",i:[]},
  "SMSM":{p:"Utama",i:["ISSI"]},
  "SNLK":{p:"Pengembangan",i:["ISSI"]},
  "SOCI":{p:"Pengembangan",i:["ISSI"]},
  "SOFA":{p:"Akselerasi",i:[]},
  "SOHO":{p:"Pengembangan",i:["ISSI"]},
  "SOLA":{p:"Pengembangan",i:["ISSI"]},
  "SONA":{p:"Pengembangan",i:["ISSI"]},
  "SOSS":{p:"Pemantauan Khusus",i:["ISSI"]},
  "SOTS":{p:"Pengembangan",i:["ISSI"]},
  "SOUL":{p:"Akselerasi",i:[]},
  "SPMA":{p:"Pengembangan",i:["ISSI"]},
  "SPRE":{p:"Akselerasi",i:[]},
  "SPTO":{p:"Utama",i:["ISSI"]},
  "SQMI":{p:"Pemantauan Khusus",i:[]},
  "SRAJ":{p:"Pengembangan",i:[]},
  "SRIL":{p:"Pemantauan Khusus",i:[]},
  "SRSN":{p:"Pengembangan",i:[]},
  "SRTG":{p:"Utama",i:["ISSI"]},
  "SSIA":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "SSMS":{p:"Utama",i:[]},
  "SSTM":{p:"Pengembangan",i:["ISSI"]},
  "STAA":{p:"Utama",i:["ISSI"]},
  "STAR":{p:"Pemantauan Khusus",i:[]},
  "STRK":{p:"Pengembangan",i:[]},
  "STTP":{p:"Pengembangan",i:["ISSI"]},
  "SUGI":{p:"Pemantauan Khusus",i:[]},
  "SULI":{p:"Pengembangan",i:["ISSI"]},
  "SUNI":{p:"Utama",i:["ISSI"]},
  "SUPA":{p:"Pengembangan",i:[]},
  "SUPR":{p:"Pemantauan Khusus",i:["ISSI"]},
  "SURE":{p:"Pengembangan",i:[]},
  "SURI":{p:"Pengembangan",i:["ISSI"]},
  "SWAT":{p:"Pemantauan Khusus",i:[]},
  "SWID":{p:"Pengembangan",i:["ISSI"]},
  "TALF":{p:"Pengembangan",i:["ISSI"]},
  "TAMA":{p:"Pemantauan Khusus",i:["ISSI"]},
  "TAMU":{p:"Pemantauan Khusus",i:["ISSI"]},
  "TAPG":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "TARA":{p:"Pemantauan Khusus",i:["ISSI"]},
  "TAXI":{p:"Pemantauan Khusus",i:["ISSI"]},
  "TAYS":{p:"Pengembangan",i:[]},
  "TBIG":{p:"Utama",i:[]},
  "TBLA":{p:"Utama",i:[]},
  "TBMS":{p:"Pengembangan",i:["ISSI"]},
  "TCID":{p:"Pengembangan",i:["ISSI"]},
  "TCPI":{p:"Pengembangan",i:["ISSI", "KOMPAS100"]},
  "TDPM":{p:"Pemantauan Khusus",i:[]},
  "TEBE":{p:"Utama",i:["ISSI"]},
  "TECH":{p:"Pemantauan Khusus",i:[]},
  "TELE":{p:"Pemantauan Khusus",i:[]},
  "TFAS":{p:"Pengembangan",i:["ISSI"]},
  "TFCO":{p:"Pemantauan Khusus",i:["ISSI"]},
  "TGKA":{p:"Pengembangan",i:["ISSI"]},
  "TGRA":{p:"Pemantauan Khusus",i:[]},
  "TGUK":{p:"Pemantauan Khusus",i:["ISSI"]},
  "TIFA":{p:"Pengembangan",i:[]},
  "TINS":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "TIRA":{p:"Pengembangan",i:["ISSI"]},
  "TIRT":{p:"Pemantauan Khusus",i:["ISSI"]},
  "TKIM":{p:"Utama",i:["ISSI"]},
  "TLDN":{p:"Pengembangan",i:["ISSI"]},
  "TLKM":{p:"Utama",i:["BUMN", "ISSI", "KOMPAS100", "LQ45"]},
  "TMAS":{p:"Utama",i:["ISSI"]},
  "TMPO":{p:"Pengembangan",i:["ISSI"]},
  "TNCA":{p:"Pengembangan",i:["ISSI"]},
  "TOBA":{p:"Utama",i:["ISSI", "KOMPAS100"]},
  "TOOL":{p:"Pengembangan",i:["ISSI"]},
  "TOPS":{p:"Pemantauan Khusus",i:[]},
  "TOSK":{p:"Pengembangan",i:["ISSI"]},
  "TOTL":{p:"Utama",i:["ISSI"]},
  "TOTO":{p:"Pengembangan",i:["ISSI"]},
  "TOWR":{p:"Utama",i:["KOMPAS100", "LQ45"]},
  "TOYS":{p:"Pemantauan Khusus",i:[]},
  "TPIA":{p:"Pengembangan",i:["ISSI", "KOMPAS100"]},
  "TPMA":{p:"Utama",i:["ISSI"]},
  "TRAM":{p:"Pemantauan Khusus",i:[]},
  "TRGU":{p:"Utama",i:[]},
  "TRIL":{p:"Pemantauan Khusus",i:[]},
  "TRIM":{p:"Utama",i:[]},
  "TRIN":{p:"Pengembangan",i:[]},
  "TRIO":{p:"Pemantauan Khusus",i:[]},
  "TRIS":{p:"Pengembangan",i:["ISSI"]},
  "TRJA":{p:"Pengembangan",i:["ISSI"]},
  "TRON":{p:"Pengembangan",i:["ISSI"]},
  "TRST":{p:"Pengembangan",i:["ISSI"]},
  "TRUE":{p:"Pengembangan",i:["ISSI"]},
  "TRUK":{p:"Pengembangan",i:["ISSI"]},
  "TRUS":{p:"Pengembangan",i:[]},
  "TSPC":{p:"Utama",i:["ISSI"]},
  "TUGU":{p:"Utama",i:[]},
  "TYRE":{p:"Pengembangan",i:["ISSI"]},
  "UANG":{p:"Pengembangan",i:["ISSI"]},
  "UCID":{p:"Utama",i:["ISSI"]},
  "UDNG":{p:"Akselerasi",i:[]},
  "UFOE":{p:"Pengembangan",i:["ISSI"]},
  "ULTJ":{p:"Utama",i:["ISSI"]},
  "UNIC":{p:"Utama",i:["ISSI"]},
  "UNIQ":{p:"Utama",i:["ISSI"]},
  "UNIT":{p:"Pengembangan",i:[]},
  "UNSP":{p:"Pemantauan Khusus",i:[]},
  "UNTD":{p:"Pengembangan",i:[]},
  "UNTR":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "UNVR":{p:"Utama",i:["ISSI", "KOMPAS100", "LQ45"]},
  "URBN":{p:"Pengembangan",i:[]},
  "UVCR":{p:"Pengembangan",i:["ISSI"]},
  "VAST":{p:"Pengembangan",i:["ISSI"]},
  "VERN":{p:"Pengembangan",i:["ISSI"]},
  "VICI":{p:"Utama",i:["ISSI"]},
  "VICO":{p:"Utama",i:[]},
  "VINS":{p:"Pengembangan",i:[]},
  "VISI":{p:"Pemantauan Khusus",i:["ISSI"]},
  "VIVA":{p:"Pemantauan Khusus",i:[]},
  "VKTR":{p:"Pengembangan",i:["ISSI"]},
  "VOKS":{p:"Pengembangan",i:["ISSI"]},
  "VRNA":{p:"Pengembangan",i:[]},
  "VTNY":{p:"Pengembangan",i:[]},
  "WAPO":{p:"Pengembangan",i:["ISSI"]},
  "WEGE":{p:"Pengembangan",i:["ISSI"]},
  "WEHA":{p:"Pengembangan",i:["ISSI"]},
  "WGSH":{p:"Akselerasi",i:[]},
  "WICO":{p:"Pemantauan Khusus",i:[]},
  "WIDI":{p:"Akselerasi",i:[]},
  "WIFI":{p:"Pengembangan",i:["KOMPAS100"]},
  "WIIM":{p:"Utama",i:[]},
  "WIKA":{p:"Pemantauan Khusus",i:[]},
  "WINE":{p:"Pengembangan",i:[]},
  "WINR":{p:"Pemantauan Khusus",i:["ISSI"]},
  "WINS":{p:"Utama",i:["ISSI"]},
  "WIRG":{p:"Pengembangan",i:["ISSI", "KOMPAS100"]},
  "WMPP":{p:"Pemantauan Khusus",i:[]},
  "WMUU":{p:"Pemantauan Khusus",i:["ISSI"]},
  "WOMF":{p:"Pengembangan",i:[]},
  "WOOD":{p:"Utama",i:["ISSI"]},
  "WOWS":{p:"Pengembangan",i:["ISSI"]},
  "WSBP":{p:"Pemantauan Khusus",i:[]},
  "WSKT":{p:"Pemantauan Khusus",i:[]},
  "WTON":{p:"Utama",i:["BUMN", "ISSI"]},
  "YELO":{p:"Pengembangan",i:["ISSI"]},
  "YOII":{p:"Pengembangan",i:[]},
  "YPAS":{p:"Pengembangan",i:["ISSI"]},
  "YULE":{p:"Pengembangan",i:[]},
  "YUPI":{p:"Utama",i:["ISSI"]},
  "ZATA":{p:"Pengembangan",i:["ISSI"]},
  "ZBRA":{p:"Pemantauan Khusus",i:[]},
  "ZINC":{p:"Pemantauan Khusus",i:[]},
  "ZONE":{p:"Pengembangan",i:["ISSI"]},
  "ZYRX":{p:"Pengembangan",i:["ISSI"]}
};

// Export untuk digunakan di index.html
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { TK, TM };
}
